### ISSUE TITLE
does not work with python3.9 or 3.10 under ubuntu 22

### ISSUE THREAD

**Issue by mkoetzing** [meesvw/bitcoin-bruteforce#3]
Process Process-8:
  File "/usr/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
Instance: 7 - Generating addresses...
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w0ackm/bitcoin-bruteforce/bruteforce.py", line 75, in OTBF
    if pk.address in wallets:
Process Process-6:
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/wallet.py", line 175, in address
    self._address = public_key_to_address(self._public_key, version=self.version)
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/format.py", line 121, in public_key_to_address
    return b58encode_check(version + ripemd160_sha256(public_key))
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/usr/lib/python3.9/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.9/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
  File "/usr/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w0ackm/bitcoin-bruteforce/bruteforce.py", line 75, in OTBF
    if pk.address in wallets:
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/wallet.py", line 175, in address
    self._address = public_key_to_address(self._public_key, version=self.version)
  File "/home/w0ackm/bitcoin-bruteforce/bruteforce.py", line 75, in OTBF
    if pk.address in wallets:
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/format.py", line 121, in public_key_to_address
    return b58encode_check(version + ripemd160_sha256(public_key))
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/wallet.py", line 175, in address
    self._address = public_key_to_address(self._public_key, version=self.version)
  File "/usr/lib/python3.9/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/format.py", line 121, in public_key_to_address
    return b58encode_check(version + ripemd160_sha256(public_key))
  File "/usr/lib/python3.9/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/usr/lib/python3.9/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
ValueError: unsupported hash type ripemd160
  File "/usr/lib/python3.9/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w0ackm/bitcoin-bruteforce/bruteforce.py", line 75, in OTBF
    if pk.address in wallets:
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/wallet.py", line 175, in address
    self._address = public_key_to_address(self._public_key, version=self.version)
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/format.py", line 121, in public_key_to_address
    return b58encode_check(version + ripemd160_sha256(public_key))
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/usr/lib/python3.9/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.9/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
Traceback (most recent call last):
  File "/usr/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w0ackm/bitcoin-bruteforce/bruteforce.py", line 75, in OTBF
    if pk.address in wallets:
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/wallet.py", line 175, in address
    self._address = public_key_to_address(self._public_key, version=self.version)
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/format.py", line 121, in public_key_to_address
    return b58encode_check(version + ripemd160_sha256(public_key))
  File "/home/w0ackm/.local/lib/python3.9/site-packages/bit/crypto.py", line 19, in ripemd160_sha256
    return new('ripemd160', sha256(bytestr)).digest()
  File "/usr/lib/python3.9/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.9/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160

**Comment by meesvw** [comment]
Could you provide me with the version of Python you're using?

**Comment by meesvw** [comment]
I've tested it on version 3.9.7 and had no problems running the code. Could you provide me what OS, Python version, Package version you use?

**Comment by mkoetzing** [comment]
hi meesvw,
i am using ubuntu22 server with python 3.9.10
regards, martin

**Comment by mkoetzing** [comment]
i installed through apt-get

**Comment by mkoetzing** [comment]
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)

**Comment by meesvw** [comment]
I've updated my Python to 3.9.10 and I experience no issues. I will try and run it on my Ubuntu server using 3.9 and 3.10. I will let you know if I find anything. For now I can only advice to reinstall the requirements.

**Comment by mkoetzing** [comment]
thank you for trying, i already reinstalled twice. i will try it on another system as well

**Comment by meesvw** [comment]
I tried to use in on my system (inside a docker container) on both the 3.9 and the 3.10 version. They work fine and when I use the debug function can see all the output. There might be a chance that your CPU is not compatible? However this would be very unlikely. Hope switching systems will workout for you!

**Comment by meesvw** [comment]
> it works with ubuntu 20

I think it's a compatibility issue within Python that causes this issue. I will close this now and might add a prompt that Ubuntu 22 isn't compatible.
